### ISSUE TITLE
Remove user_username from repository

### ISSUE THREAD

**Issue by tahnok** [uOttawa-Makerspace/MakerSpaceRepo#58]
Repository already `belongs_to :user` and so the `user_username` column is useless and will probably get out of sync if you could change your username. The column should be dropped and instead the username should be accessed _through_ the user model

**Comment by KarimChukfeh** [comment]
ill work on this issue in a separate branch after we merge this branch?

**Comment by wesleyjellis** [comment]
Ya, sounds like a plan

**Comment by KarimChukfeh** [comment]
done
