### ISSUE TITLE
Comments under repositories

### ISSUE THREAD

**Issue by Parastoo-S** [uOttawa-Makerspace/MakerSpaceRepo#59]
Users cannot delete or edit their own comments under repositories.

**Comment by KarimChukfeh** [comment]
[This PR deals with this issue by allowing users to delete their own comments.](https://github.com/uOttawa-Makerspace/MakerSpaceRepo/pull/102) (admins can delete any comment) 

Editing comments can be troublesome so for now users can delete a comment and submit it again if they want to edit?

**Comment by Parastoo-S** [comment]
@KarimChukfeh Nice! yea deleting comment is enough
