### ISSUE TITLE
Capistrano deploy leaves 2 unicorn servers running, one with old code

### ISSUE THREAD

**Issue by tahnok** [uOttawa-Makerspace/MakerSpaceRepo#80]
Deploys are currently not killing old unicorn processes, which means old code can still be running unless all unicorn processes are stopped manually before deploy. This should be automated or fixed

**Comment by KarimChukfeh** [comment]
[This PR should deal with this](https://github.com/uOttawa-Makerspace/MakerSpaceRepo/pull/100)
